steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/${PROJECT_ID}/hugo-extended", "."]
  - name: "gcr.io/${PROJECT_ID}/hugo-extended"
    args: ["--help"]

images: ["gcr.io/${PROJECT_ID}/hugo-extended"]
